# Generated by Django 4.1 on 2022-08-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_demo_link_alter_project_source_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='complete',
            field=models.BooleanField(null=True),
        ),
    ]
